### ISSUE TITLE
DxSelectBox: Using fieldTemplate causes exception

### ISSUE THREAD

**Issue by dxvladislavvolkov** [DevExpress/devextreme-angular2#106]
Below is a sample:

``` javascript
import {Component} from '@angular/core';
import {DxSelectBox, DxTemplate} from 'devextreme-angular2';

@Component({
  selector: 'my-app',
  template: `
   <div>
      <dx-select-box
          [dataSource]="products"
          fieldTemplate="myTemplate">
          <div *dxTemplate="let d = data of 'myTemplate'">
              {{d.Name}}
          </div>
      </dx-select-box>
    </div>
  `,
  directives:[
    DxSelectBox,
    DxTemplate
  ]
})
export class App{
  constructor() {
    this.products = [{
        "ID": 1,
        "Name": "HD Video Player",
        "Price": 330
    }, {
        "ID": 2,
        "Name": "SuperHD Player",
        "Price": 400
    }, {
        "ID": 3,
        "Name": "SuperPlasma 50",
        "Price": 2400
    }, {
        "ID": 4,
        "Name": "SuperLED 50",
        "Price": 1600
    }, {
        "ID": 5,
        "Name": "SuperLED 42",
        "Price": 1450
    }, {
        "ID": 6,
        "Name": "SuperLCD 55",
        "Price": 1350
    }];
  }
}
```

ORIGINAL EXCEPTION: Error: E1010 - A template should contain dxTextBox widget. See:
http://js.devexpress.com/error/16_1/E1010
ORIGINAL STACKTRACE:
Error: E1010 - A template should contain dxTextBox widget. See:
http://js.devexpress.com/error/16_1/E1010
    at d (https://unpkg.com/devextreme@16.1.6/dist/js/dx.all.js:9:10409)
    at Object.Error (https://unpkg.com/devextreme@16.1.6/dist/js/dx.all.js:9:9927)
    at t._renderTemplatedField (https://unpkg.com/devextreme@16.1.6/dist/js/dx.all.js:24:10299)
    at t._renderField (https://unpkg.com/devextreme@16.1.6/dist/js/dx.all.js:24:10015)
    at t._renderField (https://unpkg.com/devextreme@16.1.6/dist/js/dx.all.js:23:29827)
    at t._renderField (https://unpkg.com/devextreme@16.1.6/dist/js/dx.all.js:9:31683)
    at t._renderInputAddons (https://unpkg.com/devextreme@16.1.6/dist/js/dx.all.js:24:10588)
    at t._renderInputAddons (https://unpkg.com/devextreme@16.1.6/dist/js/dx.all.js:9:31683)
    at t._renderInputValueImpl (https://unpkg.com/devextreme@16.1.6/dist/js/dx.all.js:38:4950)
    at t.<anonymous> (https://unpkg.com/devextreme@16.1.6/dist/js/dx.all.js:38:4855)

**Comment by mariusbrinzaru** [comment]
How is this solved?
