### ISSUE TITLE
DxLookup validationError

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#88]
Hi,

The Red Exclamations shows properly but when you try to set the message throws an exception.

Thank You

**Comment by dxvladislavvolkov** [comment]
Hello,
In our [example](http://plnkr.co/edit/orFdsSDvy0azm5cAjgJV?p=preview), the exception is not thrown. Could you provide an example to reproduce the problem?

**Comment by Angelminster** [comment]
Hi,

It's a problem related to Templates. I think is the same in #17 . In your example change app.ts with

`import {Component} from '@angular/core';
import {DxButton, DxLookup, DxTemplate} from 'devextreme-angular2';

@Component({
  selector: 'my-app',
  template: `
    <div>
      <dx-lookup 
          [(value)]="datafield"
          [dataSource]="lookupData" 
          [isValid]="isValid()" 
          [validationError]="{ message: 'This value is invalid'}"
          showClearButton="true">
              <div *dxTemplate="let item = data of 'itemTemplate'"> {{item.id}} y {{item.name}} </div>
      </dx-lookup>
    </div>
  `,
  directives:[
    DxButton,
    DxLookup,
    DxTemplate
  ]
})
export class App {
  valid: boolean;
  lookupData: string[];
  datafield:any = {id:'item2',name:'2'};
  constructor() {
    this.valid = true;
    this.lookupData = [
        {id:'item1',name:'1'},
        {id:'item2',name:'2'},
        {id:'item3',name:'3'}
    ];
  }
  
  private isValid()
  {
    if (this.datafield == null)
    {
      return false;
    }
    return true;
  }
    
}
`

Step 1: Choose a Value
Step 2: Push Clear Button
Step 3: Try to Select Another Value Throws

VM481 zone.js:260 Uncaught EXCEPTION: Error in ./App class App - inline template:7:10
ORIGINAL EXCEPTION: TypeError: n.owner is not a function
ORIGINAL STACKTRACE:
TypeError: n.owner is not a function
    at DxTemplate.<anonymous> (https://npmcdn.com/devextreme@16.1.5/dist/js/dx.all.js:10:16343)
    at Function.each (https://npmcdn.com/jquery@2.2.4/dist/jquery.min.js:2:2911)
    at t._cleanTemplates (https://npmcdn.com/devextreme@16.1.5/dist/js/dx.all.js:10:16292)
    at t._dispose (https://npmcdn.com/devextreme@16.1.5/dist/js/dx.all.js:10:17178)
    at t._dispose (https://npmcdn.com/devextreme@16.1.5/dist/js/dx.all.js:9:5612)
    at t._dispose (https://npmcdn.com/devextreme@16.1.5/dist/js/dx.all.js:13:24380)
    at t._dispose (https://npmcdn.com/devextreme@16.1.5/dist/js/dx.all.js:9:5612)
    at HTMLDivElement.<anonymous> (https://npmcdn.com/devextreme@16.1.5/dist/js/dx.all.js:21:29887)
    at HTMLDivElement.e (https://npmcdn.com/jquery@2.2.4/dist/jquery.min.js:3:5222)
    at HTMLDivElement.dispatch (https://npmcdn.com/jquery@2.2.4/dist/jquery.min.js:3:7537)

and then

Uncaught TypeError: Cannot read property 'onPositioning' of null [...]

**Comment by Aden-git** [comment]
Hello,
 
Yes, you are right. This issue is related to templates and should be fixed in #85.

**Comment by dxvladislavvolkov** [comment]
Hello!
Version 16.1.6 solves this issue.
